### ISSUE TITLE
Help Wanted: Find transaction - POST request

### ISSUE THREAD

**Issue by george-sp** [codeburrow/nbg-fintech-hackathon-android#25]
#### HTTP request

```
POST https://nbgdemo.azure-api.net/nodeopenapi/api/transactions/rest HTTP/1.1
Content-Type: application/json
Host: nbgdemo.azure-api.net
Content-Length: 151
Ocp-Apim-Subscription-Key: ••••••••••••••••••••••••••••••••

{
  "nbgtrackid": "502497b6-808e-472c-9eaa-a6fb029f8648",
  "payload": {
    "uuid": "codeburrow.com",
    "id": "57251102db45021c1aebef35"
  }
}
```
#### Response Status

_500 Internal Server Error_
#### Response Content

```
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Origin,X-Requested-With,Content-Type,Accept,fakelogin
X-Content-Type-Options: nosniff
Date: Tue, 03 May 2016 17:09:23 GMT
X-Powered-By: Express
Content-Length: 3409
Content-Type: text/html; charset=utf-8

<html>
  <head>
    <meta charset='utf-8'> 
    <title>TypeError: Cannot read property &#39;date&#39; of undefined</title>
    <style>* {
  margin: 0;
  padding: 0;
  outline: 0;
}

body {
  padding: 80px 100px;
  font: 13px "Helvetica Neue", "Lucida Grande", "Arial";
  background: #ECE9E9 -webkit-gradient(linear, 0% 0%, 0% 100%, from(#fff), to(#ECE9E9));
  background: #ECE9E9 -moz-linear-gradient(top, #fff, #ECE9E9);
  background-repeat: no-repeat;
  color: #555;
  -webkit-font-smoothing: antialiased;
}
h1, h2 {
  font-size: 22px;
  color: #343434;
}
h1 em, h2 em {
  padding: 0 5px;
  font-weight: normal;
}
h1 {
  font-size: 60px;
}
h2 {
  margin-top: 10px;
}
ul li {
  list-style: none;
}
#stacktrace {
  margin-left: 60px;
}
</style>
  </head>
  <body>
    <div id="wrapper">
      <h1>Connect</h1>
      <h2><em>500</em> TypeError: Cannot read property &#39;date&#39; of undefined</h2>
      <ul id="stacktrace"><li> &nbsp; &nbsp;at listmore (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\implementation\transactions\implementation.ts:22:33)</li><li> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\layer.js:95:5)</li><li> &nbsp; &nbsp;at next (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\route.js:131:13)</li><li> &nbsp; &nbsp;at Route.dispatch (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\route.js:112:3)</li><li> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\layer.js:95:5)</li><li> &nbsp; &nbsp;at C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:277:22</li><li> &nbsp; &nbsp;at Function.process_params (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:330:12)</li><li> &nbsp; &nbsp;at next (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:271:10)</li><li> &nbsp; &nbsp;at Function.handle (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:176:3)</li><li> &nbsp; &nbsp;at router (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:46:12)</li><li> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\layer.js:95:5)</li><li> &nbsp; &nbsp;at trim_prefix (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:312:13)</li><li> &nbsp; &nbsp;at C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:280:7</li><li> &nbsp; &nbsp;at Function.process_params (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:330:12)</li><li> &nbsp; &nbsp;at next (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:271:10)</li><li> &nbsp; &nbsp;at Function.handle (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:176:3)</li></ul>
    </div>
  </body>
</html>
```
##### OR
- **headers:**

Access-Control-Allow-Origin →*
Content-Length →3409
Content-Type →text/html; charset=utf-8
Date →Tue, 03 May 2016 17:06:10 GMT
X-Content-Type-Options →nosniff
X-Powered-By →Express
- **body:**

```
Connect
500 TypeError: Cannot read property 'date' of undefined
   at listmore (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\implementation\transactions\implementation.ts:22:33)
   at Layer.handle [as handle_request] (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\layer.js:95:5)
   at next (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\route.js:131:13)
   at Route.dispatch (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\route.js:112:3)
   at Layer.handle [as handle_request] (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\layer.js:95:5)
   at C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:277:22
   at Function.process_params (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:330:12)
   at next (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:271:10)
   at Function.handle (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:176:3)
   at router (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:46:12)
   at Layer.handle [as handle_request] (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\layer.js:95:5)
   at trim_prefix (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:312:13)
   at C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:280:7
   at Function.process_params (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:330:12)
   at next (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:271:10)
   at Function.handle (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:176:3)
```

**Comment by rdok** [comment]
@george-sp @PadawanTony can I help with this one ?

**Comment by PadawanTony** [comment]
@rdok I just saw this. Yes please feel free to help as much as you want.

**Comment by rdok** [comment]
@george-sp  this is probably a bug from the API. I opened an issue https://github.com/i-bank/openbank-api/issues/1 Hopefully @faniskou will have a look.

**Comment by PadawanTony** [comment]
@george-sp @rdok Maybe this helps?
https://docs.google.com/document/d/1CRQFwJgBT08NGS3HeUvFshkHzXVHToN6E3NDot9nI8A/edit#heading=h.wvptksayb5k

**Comment by rdok** [comment]
@PadawanTony I'll have a good look tonight!

**Comment by zakgr** [comment]
@PadawanTony @george-sp @rdok The bug in the API, has been fixed. Let me know, if you find any other bug in the API
